- applicableMode: CAR
  default: 3
  graphQLQueryParam: true
  high: 5
  inverseKey: carReluctance
  key: carTolerance
  low: 0
  step: 0.1
  type: SLIDER
- applicableMode: BICYCLE
  default: 2
  graphQLQueryParam: true
  high: 5
  inverseKey: bikeReluctance
  key: bikeTolerance
  low: 0
  step: 0.1
  type: SLIDER
- applicableMode: WALK
  default: 2
  graphQLQueryParam: true
  high: 5
  inverseKey: walkReluctance
  key: walkTolerance
  low: 0
  step: 0.1
  type: SLIDER
- addTransportMode:
    mode: BICYCLE
    qualifier: RENT
  applicableMode: BICYCLE
  default: true
  key: allowBikeRental
  type: CHECKBOX
- applicableMode: TRANSIT
  default: false
  key: wheelchair
  label: Use Accessible Routing
  type: CHECKBOX
- addTransportMode:
    mode: BUS
  applicableMode: TRANSIT
  default: true
  iconName: Bus
  key: addBus
  type: CHECKBOX
- addTransportMode:
    mode: RAIL
  applicableMode: TRANSIT
  default: true
  iconName: Train
  key: addRail
  type: CHECKBOX
- addTransportMode:
    mode: SUBWAY
  applicableMode: TRANSIT
  default: true
  iconName: TrainSubway
  key: addSubway
  type: CHECKBOX
- addTransportMode:
    mode: TRAM
  applicableMode: TRANSIT
  default: true
  iconName: TrainTram
  key: addTram
  type: CHECKBOX
