- applicableMode: CAR
  default: 3
  graphQLQueryParam: true
  high: 5
  inverseKey: carReluctance
  key: carTolerance
  low: 0
  step: 0.1
  type: SLIDER
- applicableMode: BICYCLE
  default: 2
  graphQLQueryParam: true
  high: 5
  inverseKey: bikeReluctance
  key: bikeTolerance
  low: 0
  step: 0.1
  type: SLIDER
- applicableMode: TRANSIT
  default: true
  graphQLQueryParam: true
  key: walkReluctance
  truthValue: 5
  type: CHECKBOX
